### ISSUE TITLE
Where find   -lzbar?

### ISSUE THREAD

**Issue by shzy2012** [bieber/barcode#5]
`PS C:\cgo_test> go run .\main.go
# cgo_test/barcode
C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/mingw64/lib/../lib/libzbar.dll.a when searching for -lzbar
C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../lib/libzbar.dll.a when searching for -lzbar
C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/mingw64/lib/libzbar.dll.a when searching for -lzbar
C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../libzbar.dll.a when searching for -lzbar
C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/mingw64/lib/../lib/libzbar.dll.a when searching for -lzbar
C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../lib/libzbar.dll.a when searching for -lzbar
C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/mingw64/lib/libzbar.dll.a when searching for -lzbar
C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../libzbar.dll.a when searching for -lzbar
C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lzbar
collect2.exe: error: ld returned 1 exit status`

**Comment by bieber** [comment]
Sorry, I don't have any idea how to get the library properly set up on Windows

**Comment by garfeng** [comment]
Hello @shzy2012 , please use msys64 instead of mingw64. 

https://www.msys2.org/

``` shell
$ pacman -Sl | grep zbar
mingw32 mingw-w64-i686-zbar 0.23.1-3
mingw64 mingw-w64-x86_64-zbar 0.23.1-3 [installed]
ucrt64 mingw-w64-ucrt-x86_64-zbar 0.23.1-3
clang64 mingw-w64-clang-x86_64-zbar 0.23.1-3

```
Then install it by 
``` shell
$ pacman -S mingw-w64-x86_64-zbar

```


``` shell
$ ldd solder_real.exe | grep zbar
        libzbar-0.dll => /mingw64/bin/libzbar-0.dll (0x7ffa1a690000)

```
